name: Go
on: [push]
jobs:

  build:
    strategy:
      matrix:
        go-version: [ 'oldstable', 'stable' ]
        platform: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.platform }}

    steps:
    - name: Set up Go environment
      uses: actions/setup-go@v5
      with:
        go-version: ${{ matrix.go-version }}
    - name: Check out code into the Go module directory
      uses: actions/checkout@v4
    - name: Run tests
      run: make test