name: Go
on: [push]
jobs:

  build:
    strategy:
      matrix:
        go-version: [1.13.x, 1.14.x, 1.15.x]
        platform: [ubuntu-latest]
    runs-on: ${{ matrix.platform }}

    services:
      postgres:
        image: postgres:12
        ports:
          - 5432:5432
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: test_db
          POSTGRES_INITDB_ARGS: "--encoding=UTF-8 --locale=C"
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

      mysql:
        image: mysql:8.0
        ports:
          - "3307:3306"
        env:
          MYSQL_ROOT_PASSWORD: 'root'
          MYSQL_DATABASE: test_db

    steps:
    - name: Install Go
      if: success()
      uses: actions/setup-go@v1
      with:
        go-version: ${{ matrix.go-version }}
    - name: Check out code into the Go module directory
      uses: actions/checkout@v2
    - name: Run tests
      run: make test
      env:
        SESSION_PG_TEST_DSN: "host=localhost user=postgres password=postgres dbname=test_db sslmode=disable"
        SESSION_MY_TEST_DSN: "root:root@tcp(localhost:3307)/test_db"
